apiVersion: v1
kind: Service
metadata:
  name: {{ include "angularapp-helm-chart.fullname" . }}
  labels:
    {{- include "angularapp-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{.Values.service.targetPort}}
      protocol: TCP
      name: localhost
  selector:
    {{- include "angularapp-helm-chart.selectorLabels" . | nindent 4 }}